[workspace]
members = ["cryo", "cryo_diagnostic", "cryo_lexer", "cryo_parser", "cryo_span"]
resolver = "3"

[workspace.lints.rust]
missing_docs = "deny"
unfulfilled_lint_expectations = "forbid"

[workspace.lints.clippy]
allow_attributes = "forbid"
