[workspace]
members = ["cryo", "cryo_intern", "cryo_lexer", "cryo_parser", "cryo_span"]
resolver = "3"

[workspace.lints.rust]
missing_docs = "deny"

[workspace.lints.clippy]
allow_attributes = "forbid"
