[package]
name = "cryo_lexer"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dev-dependencies]
paste = "*"

[dependencies]
cryo_span = { version = "0.1.0", path = "../cryo_span" }
internment = "0.8.6"
sealed_trait = "0.1.1"
