[package]
name = "cryo"
version = "0.1.0"
edition = "2024"

[dependencies]
cryo_lexer = { version = "0.1.0", path = "../cryo_lexer" }
cryo_parser = { version = "0.1.0", path = "../cryo_parser" }

[lints]
workspace = true
